<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TestSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('storages')->insert([
            [
                'storageCode' => 'APA',
                'storageName' => 'Agraprana Paramitha Amartya',
                'storageAddress' => 'jalan agraprana',
                'storageNPWP' => '003.111.111.111-111',
            ],
            [
                'storageCode' => 'BBB',
                'storageName' => 'Berkah Berbagi Berkat',
                'storageAddress' => 'jalan Berkah Berbagi',
                'storageNPWP' => '005.111.111.111-111',
            ],
            [
                'storageCode' => 'CBA',
                'storageName' => 'Catur Berkat Amartya',
                'storageAddress' => 'jalan catur berkat',
                'storageNPWP' => '002.111.111.111-111',
            ],
            [
                'storageCode' => 'RBL',
                'storageName' => 'Rizky Berkah Lumintu',
                'storageAddress' => 'jalan Rizky Berkah',
                'storageNPWP' => '004.111.111.111-111',
            ],
            [
                'storageCode' => 'RQQ',
                'storageName' => 'Rorqual',
                'storageAddress' => 'aa',
                'storageNPWP' => 'aaaa213',
            ],
        ]);

        DB::table('trucks')->insert([
            [
                'no_truk' => 'truck1L',
                'truckEmail' => 'pythontest190@gmail.com',
                'truckPassword' => '$2y$10$I6HDp20xfQ.eyexX6Xu0XOmiCwmPmVGf7WuNTF6LApGFg0kxVcbIG',
                'size' => 'L',
                'mode' => 1
            ],
            [
                'no_truk' => 'truck2S',
                'truckEmail' => 'pythontest191@gmail.com',
                'truckPassword' => '$2y$10$I6HDp20xfQ.eyexX6Xu0XOmiCwmPmVGf7WuNTF6LApGFg0kxVcbIG',
                'size' => 'S',
                'mode' => 1
            ],
            [
                'no_truk' => 'truck3M',
                'truckEmail' => 'pythontest192@gmail.com',
                'truckPassword' => '$2y$10$I6HDp20xfQ.eyexX6Xu0XOmiCwmPmVGf7WuNTF6LApGFg0kxVcbIG',
                'size' => 'M',
                'mode' => 1
            ],
        ]);

        DB::table('vendors')->insert([
            [
                'vendorCode' => 'ASTRA',
                'vendorName' => 'As astra',
                'vendorAddress' => 'jln astralll',
                'vendorNPWP' => '100.90.111.111-111',
            ],
            [
                'vendorCode' => 'COC',
                'vendorName' => 'Coca',
                'vendorAddress' => 'jln coca',
                'vendorNPWP' => '100.111.111.199-111',
            ],
            [
                'vendorCode' => 'NVIDIA',
                'vendorName' => 'video graphics',
                'vendorAddress' => 'jln video',
                'vendorNPWP' => '100.90.111.111-111',
            ],
            [
                'vendorCode' => 'SPIRAL',
                'vendorName' => 'spiral sphinx',
                'vendorAddress' => 'jln assdisekai',
                'vendorNPWP' => '1213.123.1223.12',
            ],
            [
                'vendorCode' => 'WIM',
                'vendorName' => 'Wismilak Inti Makmur',
                'vendorAddress' => 'jln Wismilak Inti',
                'vendorNPWP' => '100.111.111.111-111',
            ],
        ]);

        DB::table('customers')->insert([
            [
                'customerCode' => 'DED',
                'customerName' => 'dedi',
                'customerEmail' => 'jerikuland@gmail.com',
                'customerPassword' => '$2y$10$I6HDp20xfQ.eyexX6Xu0XOmiCwmPmVGf7WuNTF6LApGFg0kxVcbIG',
                'customerAddress' => 'jln',
                'customerNPWP' => '123.111.111.111-111',
            ],
            [
                'customerCode' => 'TOM',
                'customerName' => 'tomi',
                'customerEmail' => 'fatherland@gmail.com',
                'customerPassword' => '$2y$10$I6HDp20xfQ.eyexX6Xu0XOmiCwmPmVGf7WuNTF6LApGFg0kxVcbIG',
                'customerAddress' => 'jln seen',
                'customerNPWP' => '123.112.111.111-111',
            ],
            [
                'customerCode' => 'ZEN',
                'customerName' => 'zeno',
                'customerEmail' => 'pythontest190@gmail.com',
                'customerPassword' => '$2y$10$I6HDp20xfQ.eyexX6Xu0XOmiCwmPmVGf7WuNTF6LApGFg0kxVcbIG',
                'customerAddress' => 'jln asdf',
                'customerNPWP' => '123.001.111.111-111',
            ],
        ]);

        DB::table('products')->insert([
            [
                'productCode' => 'MK-100-BB',
                'productName' => 'Mild Kapsul 100 Blueberry',
                'productPrice' => 112.12
            ],
            [
                'productCode' => 'MM-100-A',
                'productName' => 'Mild Mono 100 Acetatow',
                'productPrice' => 126.12
            ],
            [
                'productCode' => 'MM-120-A',
                'productName' => 'Mild Mono 120 Acetatow',
                'productPrice' => 121.12
            ],
            [
                'productCode' => 'RF-100-A',
                'productName' => 'Reguler Falvour 100 Acetatow',
                'productPrice' => 121.12
            ],
            [
                'productCode' => 'RF-120-A',
                'productName' => 'Reguler Falvour 120 Acetatow',
                'productPrice' => 98.12
            ],
            [
                'productCode' => 'RR-100-A',
                'productName' => 'Reguler Mono 100 Acetatow',
                'productPrice' => 112.12
            ],
            [
                'productCode' => 'RR-120-A',
                'productName' => 'Reguler Mono 120 Acetatow',
                'productPrice' => 122.12
            ],
        ]);

        DB::table('movings')->insert([
            [
                'no_moving' => '1/SJP/APA/08/2024',
                'moving_date' => '2024-08-07',
                'storageCodeSender' => 'APA',
                'storageCodeReceiver' => 'BBB',
            ],
            [
                'no_moving' => '1/SJP/RBL/08/2024',
                'moving_date' => '2024-08-16',
                'storageCodeSender' => 'RBL',
                'storageCodeReceiver' => 'RQQ',
            ],
            [
                'no_moving' => '2/SJP/APA/08/2024',
                'moving_date' => '2024-08-08',
                'storageCodeSender' => 'APA',
                'storageCodeReceiver' => 'BBB',
            ],
        ]);
        
        DB::table('orders')->insert([
            [
                'nomor_surat_jalan' => '1/SJK/NON/08/2024',
                'storageCode' => 'NON',
                'no_LPB' => null,
                'no_truk_in' => null,
                'no_truk_out' => 'truck2S',
                'vendorCode' => 'NON',
                'customerCode' => 'DED',
                'orderDate' => '2024-08-07',
                'purchase_order' => 'poNON1',
                'status_mode' => 2,
            ],
            [
                'nomor_surat_jalan' => '1/SJT/APA/08/2024',
                'storageCode' => 'APA',
                'no_LPB' => null,
                'no_truk_in' => null,
                'no_truk_out' => 'truck3M',
                'vendorCode' => 'NON',
                'customerCode' => 'DED',
                'orderDate' => '2024-08-07',
                'purchase_order' => 'potax1',
                'status_mode' => 3,
            ],
            [
                'nomor_surat_jalan' => '2/SJK/NON/08/2024',
                'storageCode' => 'NON',
                'no_LPB' => null,
                'no_truk_in' => null,
                'no_truk_out' => 'truck2S',
                'vendorCode' => 'NON',
                'customerCode' => 'TOM',
                'orderDate' => '2024-08-08',
                'purchase_order' => 'poNON2',
                'status_mode' => 2,
            ],
            [
                'nomor_surat_jalan' => '2/SJT/APA/08/2024',
                'storageCode' => 'APA',
                'no_LPB' => null,
                'no_truk_in' => null,
                'no_truk_out' => 'truck3M',
                'vendorCode' => 'NON',
                'customerCode' => 'TOM',
                'orderDate' => '2024-08-08',
                'purchase_order' => 'potax2',
                'status_mode' => 3,
            ],
            [
                'nomor_surat_jalan' => '3/SJK/NON/08/2024',
                'storageCode' => 'NON',
                'no_LPB' => null,
                'no_truk_in' => null,
                'no_truk_out' => 'truck2S',
                'vendorCode' => 'NON',
                'customerCode' => 'ZEN',
                'orderDate' => '2024-08-09',
                'purchase_order' => 'poNON3',
                'status_mode' => 2,
            ],
            [
                'nomor_surat_jalan' => '3/SJT/APA/08/2024',
                'storageCode' => 'APA',
                'no_LPB' => null,
                'no_truk_in' => null,
                'no_truk_out' => 'truck3M',
                'vendorCode' => 'NON',
                'customerCode' => 'DED',
                'orderDate' => '2024-08-16',
                'purchase_order' => 'potax3',
                'status_mode' => 3,
            ],
            [
                'nomor_surat_jalan' => 'H810005211',
                'storageCode' => 'APA',
                'no_LPB' => '1/LPB/APA/08/2024',
                'no_truk_in' => 'truck1L',
                'no_truk_out' => null,
                'vendorCode' => 'WIM',
                'customerCode' => 'NON',
                'orderDate' => '2024-08-07',
                'purchase_order' => '0203/WIM/SC/07/2024',
                'status_mode' => 1,
            ],
            [
                'nomor_surat_jalan' => 'H810005212',
                'storageCode' => 'APA',
                'no_LPB' => '2/LPB/APA/08/2024',
                'no_truk_in' => 'truck1L',
                'no_truk_out' => null,
                'vendorCode' => 'WIM',
                'customerCode' => 'NON',
                'orderDate' => '2024-08-08',
                'purchase_order' => '0203/WIM/SC/07/2024',
                'status_mode' => 1,
            ],
            [
                'nomor_surat_jalan' => 'H810005213',
                'storageCode' => 'APA',
                'no_LPB' => '3/LPB/APA/08/2024',
                'no_truk_in' => 'truck1L',
                'no_truk_out' => null,
                'vendorCode' => 'WIM',
                'customerCode' => 'NON',
                'orderDate' => '2024-08-09',
                'purchase_order' => '0203/WIM/SC/07/2024',
                'status_mode' => 1,
            ],
        ]);

        DB::table('invoices')->insert([
            [
                'nomor_surat_jalan' => 'H810005211',
                'invoice_date' => '2024-08-08',
                'no_invoice' => 'N810005183',
                'no_faktur' => '11.111.111.100-1221',
                'no_moving' => '-',
                'tax' => 11,
            ],
            [
                'nomor_surat_jalan' => 'H810005212',
                'invoice_date' => '2024-08-09',
                'no_invoice' => 'N810005184',
                'no_faktur' => '11.111.111.100-1221',
                'no_moving' => '-',
                'tax' => 11,
            ],
            [
                'nomor_surat_jalan' => 'H810005213',
                'invoice_date' => '2024-08-10',
                'no_invoice' => 'N810005185',
                'no_faktur' => '11.111.111.100-1221',
                'no_moving' => '-',
                'tax' => 11,
            ],
            [
                'nomor_surat_jalan' => '1/SJK/NON/08/2024',
                'invoice_date' => '2024-08-08',
                'no_invoice' => '1/INV/NON/08/2024',
                'no_faktur' => '1123',
                'no_moving' => '-',
                'tax' => 0,
            ],
            [
                'nomor_surat_jalan' => '2/SJK/NON/08/2024',
                'invoice_date' => '2024-08-09',
                'no_invoice' => '2/INV/NON/08/2024',
                'no_faktur' => '6666',
                'no_moving' => '-',
                'tax' => 0,
            ],
            [
                'nomor_surat_jalan' => '3/SJK/NON/08/2024',
                'invoice_date' => '2024-08-10',
                'no_invoice' => '3/INV/NON/08/2024',
                'no_faktur' => '7890',
                'no_moving' => '-',
                'tax' => 0,
            ],
            [
                'nomor_surat_jalan' => '-',
                'invoice_date' => '2024-08-07',
                'no_invoice' => '1/INV/APA/08/2024',
                'no_faktur' => '11.111.111.100-1221',
                'no_moving' => '1/SJP/APA/08/2024',
                'tax' => 11,
            ],
            [
                'nomor_surat_jalan' => '-',
                'invoice_date' => '2024-08-08',
                'no_invoice' => '2/INV/APA/08/2024',
                'no_faktur' => '11.111.111.100-1221',
                'no_moving' => '2/SJP/APA/08/2024',
                'tax' => 11,
            ],
            [
                'nomor_surat_jalan' => '1/SJT/APA/08/2024',
                'invoice_date' => '2024-08-08',
                'no_invoice' => '3/INV/APA/08/2024',
                'no_faktur' => '11.111.111.100-1221',
                'no_moving' => '-',
                'tax' => 11,
            ],
            [
                'nomor_surat_jalan' => '2/SJT/APA/08/2024',
                'invoice_date' => '2024-08-09',
                'no_invoice' => '6/INV/APA/08/2024',
                'no_faktur' => '11.111.111.100-1221',
                'no_moving' => '-',
                'tax' => 11,
            ],
            [
                'nomor_surat_jalan' => '3/SJT/APA/08/2024',
                'invoice_date' => '2024-08-10',
                'no_invoice' => '5/INV/APA/08/2024',
                'no_faktur' => '11.111.111.100-1221',
                'no_moving' => '-',
                'tax' => 11,
            ],
        ]);

        DB::table('payments')->insert([
            [
                'nomor_surat_jalan' => 'H810005212',
                'no_moving' => '-',
                'payment_date' => '2024-08-09',
                'payment_amount' => 1997000000.00,
                'payment_id' => 'PAY-2fws31ed/2024-08-09'
            ],
            [
                'nomor_surat_jalan' => 'H810005211',
                'no_moving' => '-',
                'payment_date' => '2024-08-08',
                'payment_amount' => 4595400000.00,
                'payment_id' => 'PAY-2ffo31ed/2024-08-08'
            ],
            [
                'nomor_surat_jalan' => '1/SJK/NON/08/2024',
                'no_moving' => '-',
                'payment_date' => '2024-08-08',
                'payment_amount' => 1400000000.00,
                'payment_id' => 'PAY-2ffo31xe/2024-08-08'
            ],
            [
                'nomor_surat_jalan' => '2/SJK/NON/08/2024',
                'no_moving' => '-',
                'payment_date' => '2024-08-09',
                'payment_amount' => 500000000.00,
                'payment_id' => 'PAY-2ffom1ed/2024-08-09'
            ],
            [
                'nomor_surat_jalan' => '-',
                'no_moving' => '1/SJP/APA/08/2024',
                'payment_date' => '2024-08-08',
                'payment_amount' => 815850000.00,
                'payment_id' => 'PAY-2pao31ed/2024-08-08'
            ],
            [
                'nomor_surat_jalan' => '-',
                'no_moving' => '2/SJP/APA/08/2024',
                'payment_date' => '2024-08-09',
                'payment_amount' => 500000000.00,
                'payment_id' => 'PAY-2ynoa1ed/2024-08-09'
            ],
            [
                'nomor_surat_jalan' => '1/SJT/APA/08/2024',
                'no_moving' => '-',
                'payment_date' => '2024-08-08',
                'payment_amount' => 3832275000.00,
                'payment_id' => 'PAY-2paasf1ed/2024-08-08'
            ],
            [
                'nomor_surat_jalan' => '2/SJT/APA/08/2024',
                'no_moving' => '-',
                'payment_date' => '2024-08-09',
                'payment_amount' => 1696300000.00,
                'payment_id' => 'PAY-2290i3td/2024-08-09'
            ],
        ]);

        DB::table('repacks')->insert([
            [
                'no_repack' => '1/SJR/APA/08/2024',
                'repack_date' => '2024-08-07',
                'storageCode' => 'APA',
            ],
        ]);

        DB::table('saldos')->insert([
            [
                'productCode' => 'MM-120-A',
                'storageCode' => 'APA',
                'totalQty' => 0,
                'totalPrice' => 0.00,
                'saldoMonth' => 8,
                'saldoYear' => 2024,
            ],
            [
                'productCode' => 'RR-100-A',
                'storageCode' => 'APA',
                'totalQty' => 1000,
                'totalPrice' => 485625000.00,
                'saldoMonth' => 8,
                'saldoYear' => 2024,
            ],
            [
                'productCode' => 'MM-100-A',
                'storageCode' => 'APA',
                'totalQty' => 0,
                'totalPrice' => 0.00,
                'saldoMonth' => 8,
                'saldoYear' => 2024,
            ],
            [
                'productCode' => 'RR-120-A',
                'storageCode' => 'APA',
                'totalQty' => 0,
                'totalPrice' => 0.00,
                'saldoMonth' => 8,
                'saldoYear' => 2024,
            ],
            [
                'productCode' => 'RR-120-A',
                'storageCode' => 'RBL',
                'totalQty' => -10,
                'totalPrice' => 0.00,
                'saldoMonth' => 8,
                'saldoYear' => 2024,
            ],
            [
                'productCode' => 'MM-120-A',
                'storageCode' => 'BBB',
                'totalQty' => 2000,
                'totalPrice' => 1210000000.00,
                'saldoMonth' => 8,
                'saldoYear' => 2024,
            ],
            [
                'productCode' => 'RR-120-A',
                'storageCode' => 'BBB',
                'totalQty' => 1500,
                'totalPrice' => 735000000.00,
                'saldoMonth' => 8,
                'saldoYear' => 2024,
            ],
            [
                'productCode' => 'RR-120-A',
                'storageCode' => 'NON',
                'totalQty' => 4000,
                'totalPrice' => 1950000000.00,
                'saldoMonth' => 8,
                'saldoYear' => 2024,
            ],
            [
                'productCode' => 'MM-120-A',
                'storageCode' => 'NON',
                'totalQty' => 3500,
                'totalPrice' => 2100000000.00,
                'saldoMonth' => 8,
                'saldoYear' => 2024,
            ],
            [
                'productCode' => 'MM-100-A',
                'storageCode' => 'NON',
                'totalQty' => 1500,
                'totalPrice' => 873750000.00,
                'saldoMonth' => 8,
                'saldoYear' => 2024,
            ],
            [
                'productCode' => 'RR-100-A',
                'storageCode' => 'NON',
                'totalQty' => 3000,
                'totalPrice' => 1456875000.00,
                'saldoMonth' => 8,
                'saldoYear' => 2024,
            ],
        ]);

        DB::table('purchase_orders')->insert([
            [
                'no_PO' => 'PO-6e24dbae',
                'purchaseDate' => '2025-03-01',
                'customerCode' => 'DED',
                'status_mode' => 1
            ],
            [
                'no_PO' => 'PO-c5a002c0',
                'purchaseDate' => '2025-02-23',
                'customerCode' => 'DED',
                'status_mode' => 1
            ],
        ]);

        DB::table('order_products')->insert([
            [
                'nomor_surat_jalan' => 'H810005211',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'RR-120-A',
                'qty' => 5000,
                'UOM' => 'tray',
                'price_per_UOM' => 480000.00,
                'note' => '',
                'product_status' => 'in',
            ],
            [
                'nomor_surat_jalan' => '-',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "PO-6e24dbae",
                'productCode' => 'RR-100-A',
                'qty' => 500,
                'UOM' => 'tray',
                'price_per_UOM' => 400,
                'note' => '',
                'product_status' => 'purchase_order',
            ],
            [
                'nomor_surat_jalan' => '-',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "PO-6e24dbae",
                'productCode' => 'RR-120-A',
                'qty' => 5000,
                'UOM' => 'tray',
                'price_per_UOM' => 250,
                'note' => '',
                'product_status' => 'purchase_order',
            ],
            [
                'nomor_surat_jalan' => '-',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "PO-c5a002c0",
                'productCode' => 'RR-100-A',
                'qty' => 500,
                'UOM' => 'tray',
                'price_per_UOM' => 400,
                'note' => '',
                'product_status' => 'purchase_order',
            ],
            [
                'nomor_surat_jalan' => '-',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "PO-c5a002c0",
                'productCode' => 'RR-120-A',
                'qty' => 5000,
                'UOM' => 'tray',
                'price_per_UOM' => 250,
                'note' => '',
                'product_status' => 'purchase_order',
            ],
            [
                'nomor_surat_jalan' => 'H810005211',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'MM-100-A',
                'qty' => 3000,
                'UOM' => 'tray',
                'price_per_UOM' => 580000.00,
                'note' => '',
                'product_status' => 'in',
            ],
            [
                'nomor_surat_jalan' => 'H810005212',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'RR-120-A',
                'qty' => 3000,
                'UOM' => 'tray',
                'price_per_UOM' => 500000.00,
                'note' => '',
                'product_status' => 'in',
            ],
            [
                'nomor_surat_jalan' => 'H810005212',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'MM-120-A',
                'qty' => 5000,
                'UOM' => 'tray',
                'price_per_UOM' => 600000.00,
                'note' => '',
                'product_status' => 'in',
            ],
            [
                'nomor_surat_jalan' => 'H810005213',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'RR-100-A',
                'qty' => 3000,
                'UOM' => 'tray',
                'price_per_UOM' => 485000.00,
                'note' => '',
                'product_status' => 'in',
            ],
            [
                'nomor_surat_jalan' => 'H810005213',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'MM-100-A',
                'qty' => 3000,
                'UOM' => 'tray',
                'price_per_UOM' => 585000.00,
                'note' => '',
                'product_status' => 'in',
            ],
            [
                'nomor_surat_jalan' => '1/SJK/NON/08/2024',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'RR-120-A',
                'qty' => 1000,
                'UOM' => 'tray',
                'price_per_UOM' => 500000.00,
                'note' => '',
                'product_status' => 'out',
            ],
            [
                'nomor_surat_jalan' => '1/SJK/NON/08/2024',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'MM-100-A',
                'qty' => 1500,
                'UOM' => 'tray',
                'price_per_UOM' => 605000.00,
                'note' => '',
                'product_status' => 'out',
            ],
            [
                'nomor_surat_jalan' => '2/SJK/NON/08/2024',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'RR-120-A',
                'qty' => 2000,
                'UOM' => 'tray',
                'price_per_UOM' => 500000.00,
                'note' => '',
                'product_status' => 'out',
            ],
            [
                'nomor_surat_jalan' => '2/SJK/NON/08/2024',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'RR-100-A',
                'qty' => 1000,
                'UOM' => 'tray',
                'price_per_UOM' => 480000.00,
                'note' => '',
                'product_status' => 'out',
            ],
            [
                'nomor_surat_jalan' => '3/SJK/NON/08/2024',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'MM-120-A',
                'qty' => 1500,
                'UOM' => 'tray',
                'price_per_UOM' => 615000.00,
                'note' => '',
                'product_status' => 'out',
            ],
            [
                'nomor_surat_jalan' => '3/SJK/NON/08/2024',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'MM-100-A',
                'qty' => 3000,
                'UOM' => 'tray',
                'price_per_UOM' => 605000.00,
                'note' => '',
                'product_status' => 'out',
            ],
            [
                'nomor_surat_jalan' => '-',
                'moving_no_moving' => '1/SJP/APA/08/2024',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'RR-120-A',
                'qty' => 1500,
                'UOM' => 'tray',
                'price_per_UOM' => 490000.00,
                'note' => '',
                'product_status' => 'moving',
            ],
            [
                'nomor_surat_jalan' => '-',
                'moving_no_moving' => '2/SJP/APA/08/2024',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'MM-120-A',
                'qty' => 2000,
                'UOM' => 'tray',
                'price_per_UOM' => 605000.00,
                'note' => '',
                'product_status' => 'moving',
            ],
            [
                'nomor_surat_jalan' => '1/SJT/APA/08/2024',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'RR-120-A',
                'qty' => 2500,
                'UOM' => 'tray',
                'price_per_UOM' => 485000.00,
                'note' => '',
                'product_status' => 'out_tax',
            ],
            [
                'nomor_surat_jalan' => '1/SJT/APA/08/2024',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'MM-100-A',
                'qty' => 3000,
                'UOM' => 'tray',
                'price_per_UOM' => 585000.00,
                'note' => '',
                'product_status' => 'out_tax',
            ],
            [
                'nomor_surat_jalan' => '2/SJT/APA/08/2024',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'RR-120-A',
                'qty' => 3000,
                'UOM' => 'tray',
                'price_per_UOM' => 505000.00,
                'note' => '',
                'product_status' => 'out_tax',
            ],
            [
                'nomor_surat_jalan' => '2/SJT/APA/08/2024',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'MM-120-A',
                'qty' => 3000,
                'UOM' => 'tray',
                'price_per_UOM' => 605000.00,
                'note' => '',
                'product_status' => 'out_tax',
            ],
            [
                'nomor_surat_jalan' => '3/SJT/APA/08/2024',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'RR-100-A',
                'qty' => 3000,
                'UOM' => 'tray',
                'price_per_UOM' => 490000.00,
                'note' => '',
                'product_status' => 'out_tax',
            ],
            [
                'nomor_surat_jalan' => '3/SJT/APA/08/2024',
                'moving_no_moving' => '-',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'MM-100-A',
                'qty' => 3000,
                'UOM' => 'tray',
                'price_per_UOM' => 590000.00,
                'note' => '',
                'product_status' => 'out_tax',
            ],
            [
                'nomor_surat_jalan' => '-',
                'moving_no_moving' => '1/SJP/RBL/08/2024',
                'repack_no_repack' => '-',
                'PO_no_PO' => "-",
                'productCode' => 'RR-120-A',
                'qty' => 10,
                'UOM' => 'tray',
                'price_per_UOM' => 0.00,
                'note' => '',
                'product_status' => 'moving',
            ],
            [
                'nomor_surat_jalan' => '-',
                'moving_no_moving' => '-',
                'repack_no_repack' => '1/SJR/APA/08/2024',
                'PO_no_PO' => "-",
                'productCode' => 'RR-120-A',
                'qty' => 1000,
                'UOM' => 'tray',
                'price_per_UOM' => 0.00,
                'note' => '',
                'product_status' => 'repack_start',
            ],
            [
                'nomor_surat_jalan' => '-',
                'moving_no_moving' => '-',
                'repack_no_repack' => '1/SJR/APA/08/2024',
                'PO_no_PO' => "-",
                'productCode' => 'RR-100-A',
                'qty' => 1000,
                'UOM' => 'tray',
                'price_per_UOM' => 0.00,
                'note' => '',
                'product_status' => 'repack_end',
            ],
        ]);
    }
}
